[package]
name = "training-rust-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
csv = "1.3.1"
rusqlite = {version = "0.37.0", features = ["bundled"]}
indicatif = "0.18.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_yaml = "0.9.33"